name: Minion
version: 1.0.4
api: 5.0.0
main: CLADevs\Minion\Main
author: GalaxyGames

commands:
  minion:
    description: "minion"
    permission: minion.commands
permissions:
  minion.commands:
    description: "/minion command permission"
    default: op
  minion.open.others:
    description: "Open other people osins"
    default: op
